import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { ClerkProvider} from '@clerk/nextjs'
import { dark } from "@clerk/themes";
const kanit = Kanit({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <ClerkProvider appearance={{
      elements: {
        formButtonPrimary:"bg-[#10B981] hover:bg-[#6EE7B7] text-sm normal-case"
        ,
        variables: {
          colorText: "#022C22"
        }
      },
    }}>
      <html lang="en">
      <body className={`${kanit.className}   text-[#022C22]`}>
      {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
